require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  AllowedPatterns: ['\A#'] # Allow long comments
