require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  EnabledByDefault: true

### Metrics

Metrics/MethodLength:
  Max: 20

### Bundler

Bundler/OrderedGems:
  Enabled: false

### Style

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/MixinUsage:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

### Layout

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

# RSpec

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

# Lint

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  Enabled: false
